name: Deploy to IIS Server

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and build project
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -o ./publish

      # Deploy to IIS Server
      - name: Deploy to IIS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: YOUR_SERVER_IP
          username: YOUR_USERNAME
          password: YOUR_PASSWORD
          source: ./publish/
          target: C:/inetpub/wwwroot/YOUR_PROJECT_FOLDER
